easy_admin:
    entities:
        Evenement:
            class: App\Entity\Evenement
            form:
                fields:
                    - {property: 'titre'}
                    - {property: 'sport'}
                    - {property: 'departement'}
                    - {property: 'lieu'}
                    - {property: 'adresse'}
                    - {property: 'details'}
                    - {property: 'date'}
                    - {property: 'heure'}
        Sports:
            class: App\Entity\Sports
            form:
                fields:
                    - {property: 'nom'}
                    - {property: 'slug'}
                    - {property: 'image'}
        Membres:
            class: App\Entity\Membre
            form:
                fields:
                    - {property: 'prenom'}
                    - {property: 'nom'}
                    - {property: 'pseudo'}
                    - {property: 'email'}
                    - {property: 'password'}
                    - {property: 'ville'}
                    - {property: 'departement'}
